@php
    $albums = [
        [
            'name' => 'Perjalanan Romantis',
            'slug' => 'perjalanan-romantis',
            'cover' => 'https://images.unsplash.com/photo-1519741497674-611481863552?w=900&h=700&fit=crop',
            'count' => 84,
            'period' => '2024 - 2026',
            'description' => 'Momen jalan berdua, dinner manis, dan city stroll favorit.',
        ],
        [
            'name' => 'Petualangan Alam',
            'slug' => 'petualangan-alam',
            'cover' => 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=900&h=700&fit=crop',
            'count' => 61,
            'period' => '2023 - 2026',
            'description' => 'Trip gunung, sunrise, dan pemandangan yang jadi saksi cerita kami.',
        ],
        [
            'name' => 'Date Night',
            'slug' => 'date-night',
            'cover' => 'https://images.unsplash.com/photo-1522673607200-164d1b6ce486?w=900&h=700&fit=crop',
            'count' => 43,
            'period' => '2024 - 2026',
            'description' => 'Makan malam, cafe hopping, dan momen sederhana yang hangat.',
        ],
        [
            'name' => 'Kegiatan Sehari-hari',
            'slug' => 'kegiatan-sehari-hari',
            'cover' => 'https://images.unsplash.com/photo-1530789253388-582c481c54b0?w=900&h=700&fit=crop',
            'count' => 95,
            'period' => '2023 - 2026',
            'description' => 'Rutinitas kecil yang justru paling bermakna.',
        ],
    ];

    $photos = [
        [
            'slug' => 'sunset-lake-walk',
            'title' => 'Sunset Lake Walk',
            'date' => '24 April 2026',
            'month' => 'April 2026',
            'album' => 'Perjalanan Romantis',
            'category' => 'Romantis',
            'location' => 'Situ Patenggang',
            'image' => 'https://images.unsplash.com/photo-1621184455862-c163dfb30e0f?w=1200&h=900&fit=crop',
            'size' => 'wide',
            'description' => 'Sore tenang sambil menikmati langit jingga berdua.',
        ],
        [
            'slug' => 'coffee-and-laugh',
            'title' => 'Coffee & Laugh',
            'date' => '24 April 2026',
            'month' => 'April 2026',
            'album' => 'Date Night',
            'category' => 'Date Night',
            'location' => 'Bandung',
            'image' => 'https://images.unsplash.com/photo-1522673607200-164d1b6ce486?w=1200&h=900&fit=crop',
            'size' => 'square',
            'description' => 'Ngobrol ringan dengan kopi favorit, momen kecil yang manis.',
        ],
        [
            'slug' => 'forest-trail',
            'title' => 'Forest Trail',
            'date' => '23 April 2026',
            'month' => 'April 2026',
            'album' => 'Petualangan Alam',
            'category' => 'Travel',
            'location' => 'Lembang',
            'image' => 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=1200&h=900&fit=crop',
            'size' => 'tall',
            'description' => 'Jalur hutan hijau dengan udara sejuk dan langkah yang selaras.',
        ],
        [
            'slug' => 'city-night',
            'title' => 'City Night',
            'date' => '20 April 2026',
            'month' => 'April 2026',
            'album' => 'Date Night',
            'category' => 'Romantis',
            'location' => 'Jakarta',
            'image' => 'https://images.unsplash.com/photo-1519741497674-611481863552?w=1200&h=900&fit=crop',
            'size' => 'wide',
            'description' => 'Lampu kota dan jalanan malam jadi latar cerita kita.',
        ],
        [
            'slug' => 'picnic-garden',
            'title' => 'Picnic Garden',
            'date' => '10 Maret 2026',
            'month' => 'Maret 2026',
            'album' => 'Perjalanan Romantis',
            'category' => 'Romantis',
            'location' => 'Bogor',
            'image' => 'https://images.unsplash.com/photo-1530789253388-582c481c54b0?w=1200&h=900&fit=crop',
            'size' => 'square',
            'description' => 'Siang santai dengan bekal sederhana dan obrolan panjang.',
        ],
        [
            'slug' => 'mountain-view',
            'title' => 'Mountain View',
            'date' => '08 Maret 2026',
            'month' => 'Maret 2026',
            'album' => 'Petualangan Alam',
            'category' => 'Travel',
            'location' => 'Bromo',
            'image' => 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=1200&h=900&fit=crop&crop=faces',
            'size' => 'tall',
            'description' => 'Pagi dingin, kabut tipis, dan pemandangan yang menenangkan.',
        ],
        [
            'slug' => 'rainy-window',
            'title' => 'Rainy Window',
            'date' => '18 Februari 2026',
            'month' => 'Februari 2026',
            'album' => 'Kegiatan Sehari-hari',
            'category' => 'Daily',
            'location' => 'Rumah',
            'image' => 'https://images.unsplash.com/photo-1522673607200-164d1b6ce486?w=1200&h=900&fit=crop',
            'size' => 'wide',
            'description' => 'Hujan sore ditemani playlist favorit dan secangkir teh.',
        ],
        [
            'slug' => 'weekend-breakfast',
            'title' => 'Weekend Breakfast',
            'date' => '16 Februari 2026',
            'month' => 'Februari 2026',
            'album' => 'Kegiatan Sehari-hari',
            'category' => 'Daily',
            'location' => 'Bandung',
            'image' => 'https://images.unsplash.com/photo-1530789253388-582c481c54b0?w=1200&h=900&fit=crop',
            'size' => 'square',
            'description' => 'Sarapan santai dan agenda akhir pekan yang spontan.',
        ],
        [
            'slug' => 'beach-sunrise',
            'title' => 'Beach Sunrise',
            'date' => '12 Januari 2026',
            'month' => 'Januari 2026',
            'album' => 'Perjalanan Romantis',
            'category' => 'Travel',
            'location' => 'Bali',
            'image' => 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=1200&h=900&fit=crop',
            'size' => 'wide',
            'description' => 'Menyambut matahari terbit dengan langkah kaki di pasir.',
        ],
        [
            'slug' => 'flower-market',
            'title' => 'Flower Market',
            'date' => '05 Januari 2026',
            'month' => 'Januari 2026',
            'album' => 'Date Night',
            'category' => 'Romantis',
            'location' => 'Bandung',
            'image' => 'https://images.unsplash.com/photo-1519741497674-611481863552?w=1200&h=900&fit=crop',
            'size' => 'tall',
            'description' => 'Warna-warna bunga dan suasana hangat sepanjang sore.',
        ],
        [
            'slug' => 'library-date',
            'title' => 'Library Date',
            'date' => '21 Desember 2025',
            'month' => 'Desember 2025',
            'album' => 'Kegiatan Sehari-hari',
            'category' => 'Daily',
            'location' => 'Perpustakaan Kota',
            'image' => 'https://images.unsplash.com/photo-1621184455862-c163dfb30e0f?w=1200&h=900&fit=crop',
            'size' => 'square',
            'description' => 'Tenang, fokus, dan tetap saling menemani sepanjang hari.',
        ],
        [
            'slug' => 'anniversary-dinner',
            'title' => 'Anniversary Dinner',
            'date' => '11 November 2025',
            'month' => 'November 2025',
            'album' => 'Date Night',
            'category' => 'Romantis',
            'location' => 'Jakarta',
            'image' => 'https://images.unsplash.com/photo-1522673607200-164d1b6ce486?w=1200&h=900&fit=crop',
            'size' => 'wide',
            'description' => 'Merayakan perjalanan kami dengan makan malam spesial.',
        ],
    ];
@endphp
